-- Customer Shopping Behavior: Business Questions + SQL Queries (clean copy)
-- Generated from your notebook extraction

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
       sum(purchase_amount) AS revenue
FROM customer_behavior
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount
FROM customer_behavior
WHERE discount_applied = 'Yes'
  AND purchase_amount >
    (SELECT AVG(purchase_amount)
     FROM customer_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       round(AVG(review_rating), 2) AS avg_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between Standard and Express shipping.
SELECT round(avg(purchase_amount), 2) AS avg_purchase_amount,
       shipping_type
FROM customer_behavior
WHERE shipping_type IN ('Standard',
                        'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT count(customer_id) AS total_customers,
       round(avg(purchase_amount), 2) AS avg_revenue,
       round(sum(purchase_amount), 2) AS total_revenue,
       subscription_status
FROM customer_behavior
GROUP BY subscription_status
ORDER BY total_revenue,
         avg_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE
                             WHEN discount_applied = 'Yes' THEN 1
                             ELSE 0
                         END)/count(*), 2) AS discount_rate
FROM customer_behavior
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on purchase history, and show the count of each segment.
WITH customer_type AS
  (SELECT customer_id,
          previous_purchases,
          CASE
              WHEN previous_purchases = 1 THEN 'New'
              WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
              ELSE 'Loyal'
          END AS Customer_Segment
   FROM customer_behavior)
SELECT customer_segment,
       count(*) AS customer_count
FROM customer_type
GROUP BY customer_segment
ORDER BY customer_count DESC;

-- Q8. What are the top 3 most purchased products within each category?
WITH product_category AS
  (SELECT item_purchased,
          category,
          count(customer_id) AS total_orders,
          ROW_NUMBER() OVER (PARTITION BY category
                             ORDER BY count(customer_id) DESC) AS product_rank
   FROM customer_behavior
   GROUP BY category,
            item_purchased)
SELECT product_rank,
       category,
       item_purchased,
       total_orders
FROM product_category
WHERE product_rank <= 3;

-- Q9. Are repeat buyers (more than 5 previous purchases) more likely to subscribe?
SELECT subscription_status,
       count(customer_id) AS repeat_buyers
FROM customer_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT sum(purchase_amount) AS total_revenue,
       age_group
FROM customer_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;
